"""added gov structure subscription model

Revision ID: 7aac487cf95a
Revises: 3fce45ce86a3
Create Date: 2023-05-10 13:59:48.507764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aac487cf95a'
down_revision = '3fce45ce86a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('govstructuresubscription',
    sa.Column('gov_structure_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gov_structure_uuid'], ['govstructure.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gov_structure_uuid', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('govstructuresubscription')
    # ### end Alembic commands ###
