"""renamed token field in value

Revision ID: 03dcb6b1f51c
Revises: 28bdce78152e
Create Date: 2023-05-01 13:06:09.837365

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '03dcb6b1f51c'
down_revision = '28bdce78152e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('refreshtoken', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('refreshtoken', 'value')
    # ### end Alembic commands ###
