"""added cascade delete

Revision ID: 7cfaf6e46be3
Revises: 88b145ec7d0b
Create Date: 2023-05-04 17:57:04.108939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '7cfaf6e46be3'
down_revision = '88b145ec7d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refreshtoken_user_id_fkey', 'refreshtoken', type_='foreignkey')
    op.create_foreign_key('refreshtoken_user_id_fkey', 'refreshtoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refreshtoken_user_id_fkey', 'refreshtoken', type_='foreignkey')
    op.create_foreign_key('refreshtoken_user_id_fkey', 'refreshtoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
