"""email gov structure is required


Revision ID: 3b34b34425da
Revises: f11558dd20ee
Create Date: 2023-05-19 01:32:45.762303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '3b34b34425da'
down_revision = 'f11558dd20ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('govstructure', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('govstructure', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
